name: "Build images"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and push image"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          target: base
          push: true
          tags: |
            maxxx00m/uptime-kuma-wireguard:latest

